# Generated by Django 2.2.5 on 2022-04-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='upload',
            new_name='image',
        ),
    ]
